In [11]:
import numpy as np



In [14]:
a= np.array([1, 2, 3, 4, 5])
b= np.array([[1, 2, 3],[1, 2, 3]])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.zeros(shape=(3,4)) # 3x4 matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.arange(10,16,2)

array([10, 12, 14])

In [24]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.random.rand(3,4)

array([[0.45417628, 0.734509  , 0.02945871, 0.04145751],
       [0.51878547, 0.01533944, 0.65299386, 0.97216065],
       [0.62467304, 0.21574645, 0.30419338, 0.42820282]])

In [26]:
np.random.randint(2,5,size=(3,4))

array([[3, 4, 3, 3],
       [4, 2, 2, 2],
       [2, 4, 4, 2]])